apiVersion: v1
kind: Service
metadata:
  name: my-express-app-service
spec:
  selector:
    app: express
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32201
  type: NodePort