apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: my-flask-app
        image: manojjahgirdar/my-flask-app:1.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32200
  type: NodePort